### ISSUE TITLE
Provide X-Flow-Id header for all requests

### ISSUE THREAD

**Issue by jhorstmann** [zalando-nakadi/fahrschein#113]

**Comment by jhorstmann** [comment]
- What should be the scope of the flow id? Should the same flow id be reused for reconnections or should it be a new one for each request?
 - Should this even be handled inside fahrschein or should it be a general interceptor for all http requests?

**Comment by jhorstmann** [comment]
@lukasniemeier-zalando do you have any operational insights or requirements regarding flow ids? Or do you already generate them on a lower level in the apache http client?

**Comment by lukasniemeier-zalando** [comment]
We do not use flow-ids on the requests issued by fahrschein as we do publishing the events on our own

**Comment by MALPI** [comment]
As Teams are shifting to other identifiers more and more, I don't think that it makes still sense to add that.
