### ISSUE TITLE
MetricsCollector is informed about delay of an event

### ISSUE THREAD

**Issue by i8r** [zalando-nakadi/fahrschein#126]
Nakadi events have some standard metadata (though not always present) that allows to calculate a notion of delay of the event consumption, i.e. the time between occurrence (`$.metadata.occurent_at`) and the time of consumption. This delay can help to understand the performance of a consumer (e.g. if it always keeps up with the event producer) and can be used as an alert condition if the delay exceeds a certain threshold.

To provide this, fahrschein would inspect the event if the json path `$.metadata.occurent_at` is present in the event body. If present, it would compute a duration between the given timestamp and now. It would then update the metric collector via a method `void updateDelayOfConsumption(Duration delay)`. In case the delay cannot be computed (e.g. field is not present in the event), it would call `void unknownDelayOfConsumption()`. Both methods can have default implementation that do nothing to keep backwards compatibility.

**Comment by jhorstmann** [comment]
I like the idea, this would be an interesting metric to monitor. But currently the `MetricsCollector` interface is only handling agregated data, like the number of events in a batch. Handling individual event metadata does not look like a good fit for this interface. One option could be reporting the min and max of the `occured_at` for each batch:

    void markEventsReceived(int size, Optional<OffsetDateTime> minOccuredAt, Optional<OffsetDateTime> maxOccuredAt);

**Comment by i8r** [comment]
I might give the implementation a go. (Sry, I closed the issue by accident)

**Comment by jhorstmann** [comment]
There might be a more efficient way to extract this information by using a `TokenBuffer` as in [AsPropertyTypeDeserializer](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.8.7/src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsPropertyTypeDeserializer.java#L91)

I'm currently loking into using this approach to extract the `event_type` property for mapping type hierarchies.

**Comment by jhorstmann** [comment]
Metadata could be extracted without parsing the whole data into a tree structure like this: https://github.com/zalando-incubator/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/MetadataTypeResolver.java#L117

I still think this could be easier done inside the listener.

**Comment by jhorstmann** [comment]
Closing, as this can be done inside the listener
