### ISSUE TITLE
JDK7 Compatibility

### ISSUE THREAD

**Issue by waleed-madanat** [zalando-nakadi/fahrschein#134]
Would it be possible to provide a JDK7 compatible build?

**Comment by jhorstmann** [comment]
There are some internal usages of streams and method references which should be easy to replace. Api of CursorManager might change slightly because of default methods, but otherwise there should be no problem supporting jdk7.

**Comment by waleed-madanat** [comment]
@jhorstmann sounds great, looking forward to that :smiley:

**Comment by jhorstmann** [comment]
Hm, all usages of `java.util.Optional` would also have to be replaced.

**Comment by jhorstmann** [comment]
Also `OffsetDateTime`.

**Comment by jhorstmann** [comment]
Closing due to missing feedback and interest in the feature
