### ISSUE TITLE
NakadiReader does not recover if subscription is deleted

### ISSUE THREAD

**Issue by jhorstmann** [zalando-nakadi/fahrschein#141]
Should creation of the subscription be done inside the retry loop?

    org.zalando.fahrschein.IOProblem: Problem [http://httpstatus.es/404] with status [404]: [Not Found] [Subscription with id "f935ed39-df18-429e-9fac-91b4193cf9a5" does not exist]

**Comment by jhorstmann** [comment]
There is a similar feature request for nakadi-java at dehora/nakadi-java#226

**Comment by otrosien** [comment]
I think if you delete a subscription it should be ok to restart the consumer for recreating it.
