### ISSUE TITLE
Expire locks

### ISSUE THREAD

**Issue by alnkpa** [zalando-nakadi/fahrschein#148]
The `JdbcPartitionManager` does not expire locks. In case of an application shutdown, they need to be removed manually.

**Comment by jhorstmann** [comment]
@alnkpa Is this still an issue for you or did you migrate to the subscription api? I just heard that the nakadi team would actually like to deprecate the low-level api.

**Comment by jhorstmann** [comment]
Closing, the suggestion is to move to the subscription api
