### ISSUE TITLE
Retry initial connection in case of 409 when there are no streaming slots

### ISSUE THREAD

**Issue by jhorstmann** [zalando-nakadi/fahrschein#149]
The initial connection is currently not retried, which means for the subscription api with multiple consumers there has to be a retry loop around the reading of events.

https://github.com/zalando/nakadi/blob/R2017_03_07/api/nakadi-event-bus-api.yaml#L932

**Comment by jhorstmann** [comment]
Should we add the same retry logic for the initial connection or are there status codes / problems that should not be retried? Examples could be

 - 400 on invalid access tokens
 - 403 forbidden (haven't actually seen this in practice)
 - 404 if the subscription does not exist (see #141)

**Comment by jhorstmann** [comment]
See also [riptide-exceptions ExceptionClassifier](https://github.com/zalando/riptide/blob/master/riptide-exceptions/src/main/java/org/zalando/riptide/exceptions/ExceptionClassifier.java), but I'd like to keep our logic simple and only handle `IOExeption` specially, without looking at root causes.

**Comment by lukasniemeier-zalando** [comment]
> 400 on invalid access tokens
> 403 forbidden
> 404 if the subscription does not exist

How would such errors self-heal?

I guess the retry on `409 - no free slots available` is something sensible. What do you think of having the logic that decides whether to retry or not pluggable with `409`-handling by default?

**Comment by jhorstmann** [comment]
Token or permission problems might self-heal if they are caused by issues in the tokeninfo infrastructure. Currently we would (possibly endlessly) retry all those errors, except if they are happening on the first request. That distinction is already confusing.

**Comment by whiskeysierra** [comment]
Especially 409 Conflict is kind of expected if I have more instances running than numbers of partitions, right?

**Comment by ckwozniak** [comment]
Are there any plans to solve this issue?

**Comment by otrosien** [comment]
We're planning to change it, but considering that teams may rely on the current behaviour, we're targeting this for the 2.0 release.

**Comment by otrosien** [comment]
We're looking into this as part of 2.0 but this one I'm closing as duplicate.
