### ISSUE TITLE
Documentation is unclear on error handling

### ISSUE THREAD

**Issue by mkulak** [zalando-nakadi/fahrschein#199]
README states:

> RuntimeException aborts streaming of events, the user is responsible for handling these

Ok, apparently if my listener throw RuntimeException then stream processing will be aborted.
But what about library code: can it throw RuntimeException as well? 
Should I wrap calls to `subscribe()` and `listen()` into try-catch? This moment is unclear.

I think we can improve docs here.

**Comment by jhorstmann** [comment]
Fahrschein itself should not throw `RuntimeException`, and Jackson should also wrap all exceptions in `JsonProcessingException` which is an `IOException` subclass.

If you see any `RuntimeExceptions` from fahrschein I would consider this a bug, and a try/catch and retry probably would not help in that case. Do you have a suggestion how to formulate this more clearly in the README?
