### ISSUE TITLE
Check response body when commit returns status 200

### ISSUE THREAD

**Issue by jhorstmann** [zalando-nakadi/fahrschein#207]
When committing cursors, there are 2 possible status codes for responses:

 - 204: it means that all committed cursors are newer than the previously committed cursors. It means that this consumer is making progress.

 - 200: it means that at least one of the committed cursors is stale (equal to the one already committed). When a consumer gets a 200 as response, it's important to check the response body, which includes the status for each cursors, whether it made progress or not. If all of them are marked as outdated it means that this consumer made no progress at all and is stuck. Watch out for this scenario.

See https://github.com/zalando/nakadi/blob/c2f553ff41f47714930c60200f13fa0cfbc4d21a/docs/_data/nakadi-event-bus-api.yaml#L1093

**Comment by otrosien** [comment]
We've discussed this internally, and concluded that the warning log is good enough for now.
