### ISSUE TITLE
Fahrschein thread stopped listening after retrying 12 times

### ISSUE THREAD

**Issue by wilq87** [zalando-nakadi/fahrschein#211]
happened in Zalando network yesterday around midnight:

(first retrying 11 times) main cause:
java.net.SocketException: Unexpected end of file from server
(last log from fahrschein library)
o.z.f.ExponentialBackoffStrategy         : Retry [12], sleeping for [64873] milliseconds

after that no more logs from fahrschein. Also thread that was listening was monitored and Future.isDone() was true. How is it possible that thread just stops like this silently instead of retrying further as it said it would?

**Comment by jhorstmann** [comment]
Fahrschein [only retries on `IOException`](https://github.com/zalando-nakadi/fahrschein#exception-handling), `RuntimeException` are not caught. In that case the future would be completed exceptionally, if you try to call `Future.get` it should throw the original exception. I think thread pools by default do not log this, I will add additional logging to fahrschein for this case.

If this is reproducible it would be nice to know what exception caused it, as fahrschein itself should not throw `RuntimeException` during processing.

**Comment by wilq87** [comment]
thanks @jhorstmann for fast fix! Happened only once in few months of using this client and is not reproducible. Even calling Future.get was not an option anymore as instance was restarted and everything went back to normal.
