### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by mazenmelouk** [zalando-nakadi/fahrschein#213]
Some logging(info) seems unwanted such as :
`org.zalando.fahrschein.NakadiReader      : Got [EOFException] [Stream was closed] while reading events`
I wonder if the amount of logs can be reduced

**Comment by jhorstmann** [comment]
@mazenmelouk how often are you seeing this log output? With the default settings I think nakadi would close the stream after about 1 hour. One `INFO` log per hour does not sound that much to me.

**Comment by mazenmelouk** [comment]
It was occurring more often and it was polluting more logs.
I resolved it by ignoring logs from this class for now.
