### ISSUE TITLE
Critical security update

### ISSUE THREAD

**Issue by wilq87** [zalando-nakadi/fahrschein#218]
Hey guys,
could you update your fasterxml dependency to newest version 2.9.5? The one you are using now has critical security vulnerability and fahrschein its the only one we have using those 

https://nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Afasterxml%3Ajackson-databind%3A2.9.3

**Comment by wilq87** [comment]
@lukasniemeier-zalando probably you are right. I just run our dependencies through dependency-check-maven from owasp saw you are using high risk lib and decided to let you know about that.

@jhorstmann it is a one line fix. Would take me more time to clone repo and create PR then to fix it. Can't you just release it with next update? @lukasniemeier-zalando suggested its not as critical as I thought

**Comment by otrosien** [comment]
Closed via https://github.com/zalando-nakadi/fahrschein/pull/269
