### ISSUE TITLE
Retry on not published events in case of status 207

### ISSUE THREAD

**Issue by fbrns** [zalando-nakadi/fahrschein#219]
If event publishing to nakadi returns status 207 at least one event was not published. In this case, retry to send not published events and postpone throwing an exception.

https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java#L115

**Comment by jhorstmann** [comment]
Would you expect the fahrschein library to do this automatically, or do you mean the todo at https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java#L124 which would allow the application code to more easily resend failed events?

I don't remember in which situations nakadi would respond with a 207, but I could also imagine that an immediate retry would not work, as nakadi could need some time to recover.

**Comment by piyushmor** [comment]
> Would you expect the fahrschein library to do this automatically, or do you mean the todo at https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java#L124 which would allow the application code to more easily resend failed events?
> 
> I don't remember in which situations nakadi would respond with a 207, but I could also imagine that an immediate retry would not work, as nakadi could need some time to recover.

This can happen during nakadi deployments.
