### ISSUE TITLE
Support Specifying Partitions for Streaming

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-nakadi/fahrschein#223]
**As** a consumer
**I want** to specify the partitions I want my stream to be assigned to
**So that** I can do load balance on my own.

If we implement https://nakadi.io/manual.html#/subscriptions/subscription_id/events_post to start streaming on a subscription we can offer the optional parameter `partitions`. This may be done backwards compatible to today's API using https://nakadi.io/manual.html#/subscriptions/subscription_id/events_get.

**Comment by iCubeDm** [comment]
So, after some research, there are 2 option to fix this issue:
 * rethink the design of the library to clearly separate implementations for High- and Low-level APIs
 * deprecate the Low-level API fully and fully concentrate on the subscription model of the API

Reference in the nakadi docs: https://nakadi.io/manual.html#/event-types/name/events_get
It is impossible to start streaming with POST request for the low-level API.

**Comment by iCubeDm** [comment]
One more thing. It is possible to go with "turn it around" approach. Every `StreamBuilder` will pass a lambda callback down to the `NakadiReader` specifying the particular logic for each time of API, and then the reader will just be responsible for the execution and actual reading the stream.

Reference: https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java#L149

**Comment by jhorstmann** [comment]
`NakadiReader` already has several places where the logic differs depending on whether a subscription exists, adding one more probably does not hurt. Longer term we should probably deprecate the low level api to clean this up. Are there any plans from the nakadi project to actually remove the low level api at some point? (I think it is already deprecated, right?)

**Comment by iCubeDm** [comment]
@jhorstmann Yes, as they've posted in the official documentation, all low-level related API functions are already marked as deprecated, so it definitely does make sense to remove all of this functionality.

**Comment by otrosien** [comment]
Let's not add more features to the deprecated low-level API. @lukasniemeier-zalando any objections?
