### ISSUE TITLE
Add Nakadi-Docker based integration tests

### ISSUE THREAD

**Issue by otrosien** [zalando-nakadi/fahrschein#271]
Add testcontainers-based Nakadi integration tests

**Comment by othon2000** [comment]
I like the idea of using `testcontainers` with `docker-compose.yml` file, so the developer can choose to have everything running already or let the integration test bring it up.

Example (only visible within zalando): https://github.bus.zalan.do/rapids/retail-operations-search/blob/f659394ae6e9608e99ed6593720485b9b58fd3aa/nakadi-tools/src/test/java/de/zalando/retailoperations/search/nakaditools/LocalTestWithDockerCompose.java

**Comment by otrosien** [comment]
@othon2000 I'll keep this ticket open for extending integration tests to running ITs against a local Nakadi installation.
