### ISSUE TITLE
Please release 0.19 to Maven Central

### ISSUE THREAD

**Issue by ethercrow** [zalando-nakadi/fahrschein#287]
Currently the latest there is 0.18.0: https://search.maven.org/artifact/org.zalando/fahrschein

**Comment by MALPI** [comment]
hey, @ethercrow `0.19.0` just got released. We still had some issues with the release process.

Afaik, it will take some time until it's synced to maven central. 

https://oss.sonatype.org/#nexus-search;quick~fahrschein
