### ISSUE TITLE
Upgrade to JDK11

### ISSUE THREAD

**Issue by otrosien** [zalando-nakadi/fahrschein#314]
## How to migrate Fahrschein to JDK11+?

PR's like https://github.com/zalando-nakadi/fahrschein/pull/304 start to include JDK11-features into the code base. This ticket is to define the migration steps to bump the baseline to JDK11. Important questions to ask:

- Why should we be doing it?
- How should we be doing it?
- When should we be doing it?

**Comment by MALPI** [comment]
Before merging #304 and making compromises I would prefer to actually take a conscious decision on making use of JDK11+ and set older versions EOL.

I'd suggest to merge #312 and from there on go ahead with JDK11+.

**Comment by otrosien** [comment]
The reason why I see #304 independent of a general JDK baseline bump is, that it has jdk11 in the name, so if you include it in your dependencies, you should know what you're doing.  
There are also possibilities with multi-release jars but I haven't looked into this yet.

**Comment by otrosien** [comment]
we're on JDK17 now.
