### ISSUE TITLE
Offer the option to not commit every batch (and run commit in background)

### ISSUE THREAD

**Issue by otrosien** [zalando-nakadi/fahrschein#339]
As a Nakadi user, I want to be able to speed up event consumption by not committing every batch. Instead, offer an operating mode that commits offsets periodically in the background, without blocking the event consumption.

**Describe the solution you'd like**

We should have a pluggable commit strategy, that offers the traditional commit-after-each-batch, and a more lenient, commit-in-background strategy.

**Describe alternatives you've considered**

Check with team Aruha on the expected benefit of this.

**Additional context**

https://nakadi.io/manual.html#consuming-events-from-a-subscription mentions:

> It is not necessary to commit each batch. When the cursor is committed, all events that are before this cursor in the partition will also be considered committed. 

It may have been considered and discarded in https://github.com/zalando-nakadi/fahrschein/issues/2

**Comment by othon2000** [comment]
As we discussed, it's a good idea to calculate the potential impact (throughput) on existing use cases.
Also to keep in mind: the 60 seconds max commit offset timeout from Nakadi.
