### ISSUE TITLE
Track code coverage over time / PRs

### ISSUE THREAD

**Issue by otrosien** [zalando-nakadi/fahrschein#346]
It would be important for the long-term vitailty of the project to be able to track coverage degradations with every PR.

Tasks:
* [x] Aggregate code coverage on root-level (https://github.com/zalando-nakadi/fahrschein/pull/347)
* [x] Integrate code coverage diff reporting on PR level (e.g. codecov)

**Comment by othon2000** [comment]
Some resources I found:
- https://github.com/marketplace/actions/code-coverage-summary
- https://plugins.gradle.org/plugin/net.razvan.jacoco-to-cobertura (because github supports the cobertura format)

**Comment by otrosien** [comment]
https://app.codecov.io/gh/zalando-nakadi/fahrschein
