### ISSUE TITLE
Support micrometer

### ISSUE THREAD

**Issue by otrosien** [zalando-nakadi/fahrschein#356]
**Is your feature request related to a problem? Please describe.**

Spring switched from dropwizard to micrometer. We should consider doing the same, which would actually be simplifying things, as in micrometer instead of injecting a MetricRegistry, you can just register a metric by name whenever you need it, in the same fashion as a logger in SLF4J. 

**Describe the solution you'd like**

Consider deprecating and removing fahrschein-dropwizard-metrics, and start using micrometer directly in the code.

**Describe alternatives you've considered**

Alternatively, we can keep the metrics in an extra submodule (e.g. fahrschein-micrometer-metrics), but it takes extra effort for teams to include this dependency, so we won't be instrumented by default. We could as well, bind this submodule as runtime dependency, so it can be pulled in by default. To my understanding it goes a bit against the idea of micrometer, on the other hand teams could actively exclude this dependency if needed for some reason.

**Additional context**

* https://micrometer.io/docs
* https://dzone.com/articles/spring-boot-2-migrating-from-dropwizard-to-micrometer

**Comment by RameshMalla** [comment]
I'm all in for introducing the micrometer. I would start with an easier approach by including the micrometer as an optional sub-module dependency and mention our intentions about dropping drop-wizard in the future (start with a deprecation note).
