### ISSUE TITLE
OpenTracing and OpenTelemetry Support

### ISSUE THREAD

**Issue by danielrohe** [zalando-nakadi/fahrschein#359]
**Is your feature request related to a problem? Please describe.**
The Fahrschein library already supports propagating a span context with an event between a producer and consumer. What I see is missing are helpers that transform (inject and extract) the SpanContext in a carrier specific format at the produder and consumer per event.

**Describe the solution you'd like**
Provide helper functions that can be used by clients of fahrschein library to inject current span context into event. Provider helper functions that can be used by clients of fahrschein library to span context from event.

**Comment by MALPI** [comment]
Thanks @danielrohe, wouldn't it make sense to have an extra module for opentelemetry so that it would take care of injection by default instead of only providing helpers?

**Comment by otrosien** [comment]
Does it still make sense to provide opentracing at all instead of just opentelemetry?

**Comment by MALPI** [comment]
I do think that many teams are still using opentracing, therefore I do think that it, for now, makes sense to support both.

**Comment by otrosien** [comment]
@danielrohe thank you for your contribution. We'll create a new release within the next days.
