### ISSUE TITLE
Including Serializer and Deserializer interfaces

### ISSUE THREAD

**Issue by gchudnov** [zalando-nakadi/fahrschein#376]
**Is your feature request related to a problem? Please describe.**

It would be great to add `Serializer` and `Deserializer` interfaces and remove Jackson as a dependency so that the json encoder/decoder decision is not hardcoded.

It will simplify using this library, e.g. in Scala where different JSON encoding / decoding libraries are more common.

**Describe the solution you'd like**

Remove `Jackson` as am explicit dependency and add [Serializer](https://github.com/apache/kafka/blob/2.0/clients/src/main/java/org/apache/kafka/common/serialization/Serializer.java) and [Deserializer](https://github.com/apache/kafka/blob/2.0/clients/src/main/java/org/apache/kafka/common/serialization/Deserializer.java) interfaces.

Another [reference](https://kafka.apache.org/20/documentation/streams/developer-guide/datatypes)

An additional opt-in library might provide the bindings to Jackson.
Other library users will be able to provide their own serializes and deserializers.

**Describe alternatives you've considered**

in a scala project:

- changing the json codec in a project
- using jackson-module-scala, but that is a bit complicated for external case clases.
- using several codecs

**Comment by ePaul** [comment]
Is there a problem with having multiple JSON-libraries in the same application (apart from "redundancy")?

I guess one issue is that then you somehow need to configure both Jackson and whatever other JSON-library we have for our objects to be sent.

**Comment by gchudnov** [comment]
yes, and as a result complexity in the code might increase as well
