### ISSUE TITLE
Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by rob-h-w** [zalando-nakadi/fahrschein#404]
The recently integrated spring boot starter is still using SB 2.

Migration to 3 is needed.

**Comment by vishalsingh2972** [comment]
@rob-h-w  can you assign this to me?

**Comment by rasouli** [comment]
Hi 🙌🏻 
I was curious what is the progress on farschein spring boot starter 3 integration? I was wondering if I could help.

**Comment by otrosien** [comment]
done (check out the 2.0.0 RC releases)
