### ISSUE TITLE
Remove SB Starter dependency on Lombok & Guava

### ISSUE THREAD

**Issue by rob-h-w** [zalando-nakadi/fahrschein#405]
The Spring Boot Starter depends on Lombok & Guava.

These can be replaced with some standard Java code to reduce the BOM size.

**Comment by otrosien** [comment]
- Guava is done: https://github.com/zalando-nakadi/fahrschein/pull/412
- Lombok is used a lot, pulling it out may not be worth the hassle unless someone wants to dedicate time to cleaning all that delombok mess up: https://github.com/zalando-nakadi/fahrschein/pull/413
