### ISSUE TITLE
Add support for multiple consumers for per subscription

### ISSUE THREAD

**Issue by kyle-a-wong** [zalando-nakadi/fahrschein#409]
**Is your feature request related to a problem? Please describe.**
When listening to a subscription, there is not built in support for defining multiple consumers. That is, if you want to increase throughput for a subscription, the options are to manually, eg:
```
    Executor ex = Executors.newFixedThreadPool(3);
    ex.execute(nakadiClient.stream(subscription).runnable(myClass, myListener).unchecked().run());
    ex.execute(nakadiClient.stream(subscription).runnable(myClass, myListener).unchecked().run());
    ex.execute(nakadiClient.stream(subscription).runnable(myClass, myListener).unchecked().run());
``` 
or scale to have multiple instances of an application, each with a single listener.

**Describe the solution you'd like**
It would be nice for the stream builder to accept configurations to support more parallelism for event consumption (ie. a number of consumers per subscription and an executor)

**Comment by ePaul** [comment]
@kyle-wong-knewton Does your "manual" example code actually work? It looks to me like this will also get you errors when committing cursors, for the same reason as in #222.

@otrosien #222 is about having multiple subscriptions for the same event type (in the same NakadiClient), this one is about multiple consumer connections to the same subscription, so in principle two different features.

Though it seems like the problem behind #222 (having the stream-ID in memory per event-type) might also become a problem for this feature, as it will likely still commit cursors to the wrong stream.

This in turn implies that a solution to #222 should not just replace the event_type → stream-ID map with an subscription → stream-ID map, but actually store the stream-ID per consumer object.

**Comment by kyle-wong-knewton** [comment]
@ePaul thanks for bringing this up. I only tested via some local testing, but ultimately didn't implement this in our production service. When doing my local testing, i didn't encounter any errors with committing cursors (that i recall anyway), but I'll go back to my tests and see if i notice anything.

**Comment by otrosien** [comment]
I haven't tried this but can't this be achieved by building multiple subscription objects from nakadiClient? Or even instanciating multiple NakadiClients (you can share the same http request factory of course)?

**Comment by ePaul** [comment]
Using multiple NakadiClient objects should work (they are independent). I'm unsure about having multiple subscription objects with the same subscription ID in the same NakadiClient – I suspect that will fail again due to #222.
