### ISSUE TITLE
Metadata is missing the proper equals and hashcode implementations

### ISSUE THREAD

**Issue by fixxer** [zalando-nakadi/fahrschein#417]
**Is your feature request related to a problem? Please describe.**
Effectively immutable class Metadata is missing `equals` and `hashCode`. This causes inconveniences in user code when we implement Event interface, especially in tests when we want to assert two events equality.

```java
    @Test
    public void shouldHaveProperIdentity() {
        final String eventType = "TEST-EVENT-TYPE";
        final String eid = "a3e25946-5ae9-3964-91fa-26ecb7588d67";
        final String partition = "partition1";
        final String version = "v1";
        final String publishedBy = "unauthenticated";
        final OffsetDateTime occurredAt = OffsetDateTime.now(ZoneOffset.UTC);
        final OffsetDateTime receivedAt = OffsetDateTime.now(ZoneOffset.UTC);
        final String flowId = UUID.randomUUID().toString();

        final Metadata metadata1 = new Metadata(eventType, eid, occurredAt, partition, version, publishedBy, receivedAt, flowId, Collections.emptyMap());
        final Metadata metadata2 = new Metadata(eventType, eid, occurredAt, partition, version, publishedBy, receivedAt, flowId, Collections.emptyMap());

        assertEquals(metadata1, metadata2);
    }
```

**Describe the solution you'd like**
Add a proper implementation of the equals and hashcode methods to the Metadata class.

**Describe alternatives you've considered**
Each user implementation of Event may have a custom equals and hashcode implementations checking the Metadata internals. This approach is cumbersome and may be not consistent across the user code.

**Comment by mesut** [comment]
Thank you for your contribution @fixxer
