### ISSUE TITLE
Sensible default value for ExponentialBackoffStrategy's maxRetries

### ISSUE THREAD

**Issue by Birne94** [zalando-nakadi/fahrschein#459]
**Is your feature request related to a problem? Please describe.**

Our team recently started using the `ExponentialBackoffStrategy` based on the recommended configuration from the README:
```java
NakadiClient nakadiClient = NakadiClient.builder(NAKADI_URI, new JavaNetRequestFactory(ContentEncoding.GZIP))
        .withPublishingRetryAndBackoffStrategy(PublishingRetryStrategies.FAILED_ONLY, new ExponentialBackoffStrategy()) // recommended retry configuration
        .build();

```
While the snippet above is for event publishing, we applied the same logic for our event consumer:
```java
nakadiClient.stream(ourSubscription())
  .withObjectMapper(objectMapper)
  .withStreamParameters(StreamParameters().withBatchLimit(1))
  .withBackoffStrategy(ExponentialBackoffStrategy())
```

Today we found out that our application has not had a successful connection to Nakadi for the past 5 days (subscription could not be found). After checking the logs, we saw messages like the following:
```
Got [IOProblem] on retry [651]:
org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [404]: [Not Found] [Subscription with id "d069dde2-b1d2-48ad-aa6f-b1df83b09a11" does not exist]
```
Looking at the remaining logs, the application has been retrying for the past 5 days without raising any exceptions. All logs we found were just on `WARN` level. As a result, our alerts checking for messages on `ERROR` level did not trigger. The reason why we had those errors in the first place is the same as #408, probably having a sensible maximum number of retries and restarting the containers would resolve that issue as well.

**Describe the solution you'd like**

Given that the snippet shared above is the _"recommended retry configuration"_, I would expect a failure to connect to Nakadi eventually results in an error being thrown instead of an infinite stream of warnings. We found a small mention of the retry limit [here](https://github.com/zalando-nakadi/fahrschein?tab=readme-ov-file#backoff-strategies), however this part seems easy to miss.

I am also not sure if it makes sense to retry 4xx in general since they are most likely not going to be resolved without manual intervention anyway.

**Describe alternatives you've considered**

Our team will configure `maxRetries` manually to work around the issue, but this behavior was very surprising for us. Alternatively, changing the recommended example to pass a maximum number of retries can be a solution as well that would not break backwards compatibility.

**Additional context**

<details>
<summary>log of initial failure</summary>

```
{
  "timestamp": "2024-01-05T09:30:29.836Z",
  "level": "WARN",
  "thread": "pool-6-thread-1",
  "logger": "org.zalando.fahrschein.ExponentialBackoffStrategy",
  "message": "Got [IOProblem] on retry [0]",
  "context": "default",
  "exception": "org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [404]: [Not Found] [Subscription with id \"d069dde2-b1d2-48ad-aa6f-b1df83b09a11\" does not exist]\n\tat org.zalando.fahrschein.ProblemHandlingRequest.handleProblem(ProblemHandlingRequest.java:104)\n\tat org.zalando.fahrschein.ProblemHandlingRequest.execute(ProblemHandlingRequest.java:52)\n\tat org.zalando.fahrschein.NakadiReader.openJsonInput(NakadiReader.java:154)\n\tat org.zalando.fahrschein.ExponentialBackoffStrategy.call(ExponentialBackoffStrategy.java:74)\n\tat org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:313)\n\tat org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:265)\n\tat org.zalando.fahrschein.IORunnable.lambda$unchecked$0(IORunnable.java:13)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
}
```

</details>

<details>
<summary>log of continued failure after 4 days</summary>

```
{
  "timestamp": "2024-01-09T20:19:58.933Z",
  "level": "WARN",
  "thread": "pool-6-thread-1",
  "logger": "org.zalando.fahrschein.ExponentialBackoffStrategy",
  "message": "Got [IOProblem] on retry [651]",
  "context": "default",
  "exception": "org.zalando.fahrschein.IOProblem: Problem [about:blank] with status [404]: [Not Found] [Subscription with id \"d069dde2-b1d2-48ad-aa6f-b1df83b09a11\" does not exist]\n\tat org.zalando.fahrschein.ProblemHandlingRequest.handleProblem(ProblemHandlingRequest.java:104)\n\tat org.zalando.fahrschein.ProblemHandlingRequest.execute(ProblemHandlingRequest.java:52)\n\tat org.zalando.fahrschein.NakadiReader.openJsonInput(NakadiReader.java:154)\n\tat org.zalando.fahrschein.ExponentialBackoffStrategy.call(ExponentialBackoffStrategy.java:74)\n\tat org.zalando.fahrschein.NakadiReader.runInternal(NakadiReader.java:313)\n\tat org.zalando.fahrschein.NakadiReader.run(NakadiReader.java:265)\n\tat org.zalando.fahrschein.IORunnable.lambda$unchecked$0(IORunnable.java:13)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"
}
```

</details>

**Comment by otrosien** [comment]
Hello @Birne94,

thanks for reaching out to us with this extensive analysis. I think your issue happened because while consuming, your subscription was deleted. This is AFAIK the only way to get a 404 unless you're using a hard-coded subscription for connecting to Nakadi (see https://github.com/zalando-nakadi/fahrschein/issues/408). 

We will check if we can avoid retrying 404.
