### ISSUE TITLE
Improve Error Logging for deserialization during event batch parsing

### ISSUE THREAD

**Issue by as-belcastro** [zalando-nakadi/fahrschein#465]
**Is your feature request related to a problem? Please describe.**
It's been seen that, in some unknown ways, alien events can pop up in Nakadi event types and as expected they do not comply with event type schema therefore deserialization issues occur. When investigating these issues the log doesn't tell us what partition, offset nor provides the alien events making investigation and resolution much harder.

**Describe the solution you'd like**
Improve error logging for Nakadi Reader to provide as much information as possible in case of issues during batch parsing.

**Describe alternatives you've considered**
Considered a localized workaround in the client though it'd leave fahrschein same behaviour across projects.

**Comment by otrosien** [comment]
Closed via https://github.com/zalando-nakadi/fahrschein/pull/466 . Thanks @as-belcastro
