### ISSUE TITLE
Rename `markMessageSuccessfullyProcessed`?

### ISSUE THREAD

**Issue by jhorstmann** [zalando-nakadi/fahrschein#79]
@tmuehl in https://github.com/zalando-incubator/fahrschein/blob/0.4.4/src/main/java/org/zalando/fahrschein/NakadiReader.java#L270 `markMessageSuccessfullyProcessed` is only called if there were events contained in the batch. Would it make sense to rename if to `markEventsProcessed`, maybe event with the event count as parameter?

**Comment by tmuehl** [comment]
Honestly, I don't care. :)
I don't see any argument against renaming it and passing in the number of events.

**Comment by AdnanKukuljac** [comment]
@jhorstmann this is pretty old, should we close this issue or rename as proposed?

**Comment by jhorstmann** [comment]
Closing, no good reason to change the api after such a long time.
